# Generated by Django 4.2.13 on 2024-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
