# Generated by Django 4.2.13 on 2024-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resources_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
