# Generated by Django 4.2.13 on 2024-07-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resources_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='resources',
            name='updated_on',
        ),
    ]
