# Generated by Django 4.2.13 on 2024-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resources_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
