# Generated by Django 4.2.13 on 2024-07-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_suggestion_delete_suggestresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='slug',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
