# Generated by Django 4.2.13 on 2024-07-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_remove_suggestion_slug_suggestion_website_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='resources',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='website',
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
